// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                = require("bs-platform/lib/js/list.js");
var Curry               = require("bs-platform/lib/js/curry.js");
var React               = require("react");
var Pervasives          = require("bs-platform/lib/js/pervasives.js");
var ReasonReact         = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./utils/utils.bs.js");

 require('./companyList.css') 
;

var component = ReasonReact.statelessComponent("CompanyList");

function make(companies, employees, selectedCompany, onSelectCompany, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "row gutters main"
                }, React.createElement("div", {
                      className: "col col-3"
                    }, React.createElement("ul", {
                          className: "unstyled"
                        }, Utils$ReactTemplate.listToElement(List.map((function (c) {
                                    var match = +(c[/* name */0] === selectedCompany);
                                    return React.createElement("li", {
                                                key: c[/* name */0],
                                                className: match !== 0 ? "active" : "",
                                                onClick: (function () {
                                                    return Curry._1(onSelectCompany, c[/* name */0]);
                                                  })
                                              }, Utils$ReactTemplate.str(c[/* name */0]));
                                  }), companies)))), React.createElement("div", {
                      className: "col col-9"
                    }, React.createElement("table", {
                          className: "bordered"
                        }, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, Utils$ReactTemplate.str("First name")), React.createElement("th", undefined, Utils$ReactTemplate.str("Last name")), React.createElement("th", undefined, Utils$ReactTemplate.str("Birthday")), React.createElement("th", undefined, Utils$ReactTemplate.str("Salary")))), React.createElement("tbody", undefined, Utils$ReactTemplate.listToElement(List.map((function (e) {
                                        return React.createElement("tr", {
                                                    key: e[/* lastName */1]
                                                  }, React.createElement("td", undefined, Utils$ReactTemplate.str(e[/* firstName */0])), React.createElement("td", undefined, Utils$ReactTemplate.str(e[/* lastName */1])), React.createElement("td", undefined, Utils$ReactTemplate.str(e[/* birthday */2])), React.createElement("td", undefined, Utils$ReactTemplate.str("$" + Pervasives.string_of_float(e[/* salary */3]))));
                                      }), employees))))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/*  Not a pure module */
