// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry               = require("bs-platform/lib/js/curry.js");
var React               = require("react");
var ReasonReact         = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./utils/utils.bs.js");

 require('./header.css') 
;

var component = ReasonReact.statelessComponent("Header");

function executeQuery($$event, action) {
  if ($$event.keyCode === 13) {
    $$event.preventDefault();
    return Curry._1(action, /* () */0);
  } else {
    return 0;
  }
}

function make(query, onQueryUpdate, onQueryExecute, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  id: "top"
                }, React.createElement("div", {
                      id: "top-brand"
                    }, Utils$ReactTemplate.str("Company browser")), React.createElement("nav", {
                      id: "top-nav-main"
                    }, React.createElement("input", {
                          className: "searchBox",
                          placeholder: "Search",
                          value: query,
                          onKeyDown: (function ($$event) {
                              return executeQuery($$event, onQueryExecute);
                            }),
                          onChange: onQueryUpdate
                        })));
    });
  return newrecord;
}

exports.component    = component;
exports.executeQuery = executeQuery;
exports.make         = make;
/*  Not a pure module */
