// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                = require("bs-platform/lib/js/list.js");
var React               = require("react");
var Pervasives          = require("bs-platform/lib/js/pervasives.js");
var ReasonReact         = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./utils/utils.bs.js");

var component = ReasonReact.statelessComponent("SearchResults");

function make(results, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "row gutters main"
                }, React.createElement("div", {
                      className: "col col-12"
                    }, React.createElement("table", {
                          className: "bordered"
                        }, React.createElement("tbody", undefined, Utils$ReactTemplate.listToElement(List.mapi((function (idx, result) {
                                        return React.createElement("tr", {
                                                    key: Pervasives.string_of_int(idx)
                                                  }, React.createElement("td", undefined, Utils$ReactTemplate.str(result)));
                                      }), results))))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
